name: 'Bot Notifications'
description: 'A simple bot notification by github actions'
author: 'hb0730 <1278032416@qq.com>'
inputs:
  webhook:
    required: true
    description: 'The webhook url'
  secret:
    required: false
    description: 'The secret'
  bot:
    required: true
    description: 'The bot type,default: feishu'
    default: 'feishu'
  msg_type:
    required: false
    description: 'The msg type,default: text'
    default: 'text'
  simplified:
    required: false
    description: 'The content is simplified'
    default: 'true'
  content:
    required: false
    description: 'The content'
    default: 'Hello World'
outputs:
  response:
    description: 'The bot response'
runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  color: 'purple'
  icon: 'bell'
