name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
      - 'v*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          npm install
          npm run all
  feishu-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Text Tests
        uses: ./
        with:
          webhook: ${{ secrets.FEISHU_WEBHOOK }}
          secret: ${{ secrets.FEISHU_SECRET }}
          bot: 'feishu'
          msg_type: 'text'
          content: |
            hahahah
            from github action test
            repository: ${{ github.repository }}
            committer: ${{ github.actor }}
            compare: ${{ github.event.compare }}
            job status: ${{ job.status }}
      - name: Post Test
        uses: ./
        with:
          webhook: ${{ secrets.FEISHU_WEBHOOK }}
          secret: ${{ secrets.FEISHU_SECRET }}
          bot: 'feishu'
          msg_type: 'post'
          content: |
            post:
              zh_cn:
                title: 我是一个标题
                content:
                - - tag: text
                    un_escape: true
                    text: '第一行&nbsp;:'
                  - tag: a
                    text: 超链接 repo
                    href: ${{ github.repository }}
                  - tag: at
                    user_id: ou_18eac85d35a26f989317ad4f02e8bbbb
                - - tag: text
                    text: '第二行 :'
                  - tag: text
                    text: 文本测试
                - - tag: img
                    image_key: d640eeea-4d2f-4cb3-88d8-c964fab53987
                    width: 300
                    height: 300
      - name: Md Test
        uses: ./
        with:
          webhook: ${{ secrets.FEISHU_WEBHOOK }}
          secret: ${{ secrets.FEISHU_SECRET }}
          bot: 'feishu'
          msg_type: 'interactive'
          content: |
            card:
              elements:
              - tag: markdown
                content: |
                  #### 构建信息
                  > - 应用名称:  ${{ github.repository }}
              header:
                title:
                  content: '构建信息'
                  tag: plain_text
